
          
name: Keep Repl Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Replit App
        run: curl -s "https://8b9d424b-d20c-4798-9537-592afb776a3d-00-3k7ca1iakjcqu.pike.replit.dev"
